#!/usr/bin/env bash
# a bash script that accepts either one or two arguments namely
# domain and subdomain and displays info about subdomains.

func () {
ans=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -1 )
echo "$2 $ans" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6 }'
}

if [ "$#" -lt 1 ]
then
echo "Usage: 0-world_wide_web domain subdomain[optional]"
elif [ "$#" -eq 1 ]
then
  func "$1" "www"
  func "$1" "lb-01"
  func "$1" "web-01"
  func "$1" "web-02"
else
func "$1" "$2"
fi
