#!/usr/bin/env bash
# a bash script that Install nginx on your web-01 server
# listening on port 80 with a GET request

sudo app-get update
sudo apt-get install -y nginx
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
