#!/usr/bin/env bash
# a bash script that Configures Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx
echo "301 Moved Permanently" > /etc/nginx/html/index.html
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html;
	location /redirect_me {
		return 301 https://github.com/iolowookere217;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
