#!/usr/bin/env bash
# a bash script that Configures Nginx server so that /redirect_me is redirecting to another page.

string_to_replace="server_name _;"
new_string="server_name _;\n\n\nlocation\/redirect_me {\n\treturn 301 https:\/\/github.com\/iolowookere217;\n}"


sed -i "s/$string_to_replace/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
