#!/usr/bin/env bash
# a bash script that Configures Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status


string_to_replace="server_name _;"

new_string="server_name _;\n\terror_page 404 \/404.html; \nlocation = \/404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/$string_to_replace/$new_string/" /etc/nginx/sites-available/default
sudo service nginx restart
