#!/usr/bin/env bash
# a bash script that Configures Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_to_replace="server_name _;"

new_string="server_name _;\n\terror_page 404 \/404.html; \nlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/$string_to_replace/$new_string/" /etc/nginx/sites-available/default

# http response header configuration
sudo sed -i '/^http (/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf 

sudo service nginx restart
