#!/usr/bin/env bash
# a bash script that Configures Nginx server so that /redirect_me is redirecting to another page.

# install nginx
sudo apt-get update
sudo apt-get install -y nginx

# firewall config
ufw allow 'Nginx HTTP'


# custom page
echo "Hello World!" > /var/www/html/index.html

# Redirection
string_to_replace="server_name _;"
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/iolowookere217 permanent;"
sudo sed -i "s/$string_to_replace/$new_string/" /etc/nginx/sites-available/default

# custom not a page
echo "Ceci n'est pas une page" > /var/www/html/404.html

string_to_replace="listen 80 default_server;"
new_string="listen 80 default_server;\n\terror_page 404 \/404.html; \nlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/$string_to_replace/$new_string/" /etc/nginx/sites-available/default

sudo sed -i '/^http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

nginx -s reload
