#!/usr/bin/env bash
# a bash script that ensures Ubuntu container’s Nginx installation is listening on port 80
cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
