#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

# using while / for / until

count=1
while [ $count -lt 11 ]
do
if [ $count = 4 ]
then
echo "bad luck"
elif [ $count = 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((count+=1))
done
