#!/usr/bin/env bash

# a Bash script that displays the content of the current working directory.
# in a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

for i in *
do
    echo "$i" | cut -d'-' -f2
done

