#!/usr/bin/env bash
# Fixes the issue with the web server
# DOCKER_CONT_ID=$(docker ps | grep 'holbertonschool/265-0' | cut -d ' ' -fi)
# docker exec -i "$DOCKER_CONT_ID" \
#    /bin/bash -c  "echo 'Hello Holberton' > /var/www/html/index.html"
# docker exec -i "$DOCKER_CONT_ID" /bin/bash -c "sudo service apache2 start"
echo 'Hello Holberton' > /var/www/html/index.thml
sudo service apache2 start
